apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ .Values.identityName }}
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
  labels:
    {{- include "external-dns-identity.labels" . | nindent 4 }}
spec:
  type: 0
  resourceID: {{ .Values.userIdentityId }}
  clientID: {{ .Values.userIdentityClientId }}
