[certificatesResolvers.leresolver.acme]
    email = "jakub.fijalkowski@leancode.pl"
    logging = true
    [certificatesResolvers.leresolver.acme.tlsChallenge]
[metrics]
    [metrics.datadog]
        addEntryPointsLabels = true
        addServicesLabels = true
[tracing]
    backend = "datadog"
    serviceName = "traefik"
    spanNameLimit = 100
    [tracing.datadog]
