kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: traefik-acme
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0600
  - uid=0
  - gid=0
parameters:
  skuName: Standard_LRS
