apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ .Values.identityName }}-binding
  labels:
    {{- include "external-dns-identity.labels" . | nindent 4 }}
spec:
  azureIdentity: {{ .Values.identityName }}
  selector: {{ .Values.identityName }}
